apiVersion: v2
name: my-platform-song
description: Helm chart
type: application
version: "5.0"
appVersion: "5.0"
dependencies:
  - name: app-resource-service
    repository: file://./charts/app-resource-service
    version: "5.0"
  - name: app-song-service
    repository: file://./charts/app-song-service
    version: "5.0"
  - name: db-resource-service
    repository: file://./charts/db-resource-service
    version: "1.0"
  - name: db-song-service
    repository: file://./charts/db-song-service
    version: "1.0"