# db-resource-service PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-rs-pv
  namespace: k8s-program
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app-data"

---
# db-resource-service PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-rs-pvc
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
