---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: k8s-program
type: Opaque
stringData:
  RS_SPRING_DATASOURCE_USERNAME: rsuser
  RS_SPRING_DATASOURCE_PASSWORD: rspwd
  SS_SPRING_DATASOURCE_USERNAME: ssuser
  SS_SPRING_DATASOURCE_PASSWORD: sspwd